# Generated by Django 4.0.4 on 2022-05-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complented',
            new_name='completed',
        ),
    ]
